#!/bin/bash

DIR_VAR=var
if [ ! -d "$DIR_VAR" ]; then
    mkdir $DIR_VAR
fi

build_docker_containers
{
    (
        cd docker || exit
        docker compose build
    )
}

build_docker_containers
bin/composer install
