services:
  datamaps-nginx:
    container_name: "datamaps-nginx"
    image: datamaps-nginx:latest
    build:
      context: ../.
      dockerfile: docker/nginx/Dockerfile
    command: [nginx, "-g", "daemon off;"]
    depends_on:
      - datamaps-php
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - "$PWD/..:/var/datamaps"
    ports:
      - "127.0.0.1:10180:80"
    networks:
      - datamaps-network

  datamaps-php:
    container_name: "datamaps-php"
    image: datamaps-php:latest
    build:
      context: .
      dockerfile: php/Dockerfile
      tags:
        - latest
    user: 1000:1000
    volumes:
      - ../../log:/var/datamaps/log
      - "$PWD/..:/var/datamaps"
      - "$PWD/..:$PWD/.."
    working_dir: $PWD/..
    depends_on:
      datamaps-mariadb:
        condition: service_started
    networks:
      - datamaps-network

  datamaps-mariadb:
    image: datamaps-mariadb:latest
    container_name: "datamaps-mariadb"
    build:
      context: .
      dockerfile: mariadb/Dockerfile
      tags:
        - latest
    restart: always
    volumes:
      - datamaps-db:/var/lib/mysql
      - ../../mariabackup:/backup
    env_file:
      - ./mariadb/db.env
    networks:
      - datamaps-network

  datamaps-swagger-ui:
    image: swaggerapi/swagger-ui:v5.10.3
    container_name: "datamaps-swagger-ui"
    restart: always
    environment:
      PORT_IPV6: 8080
      SUPPORTED_SUBMIT_METHODS: "['get', 'post', 'put', 'delete', 'patch']"
      URLS: "[ \
        { url: 'http://127.0.0.1:10180/doc.php', name: 'Datamaps localhost' }, \
        { url: 'https://datamaps.logipro.fr/doc.php', name: 'Datamaps Logipro' }, \
        { url: 'https://accidentprediction.fr/datamaps/doc.php', name: 'Datamaps accidentprediction' } \
        ]"
    ports:
      - "127.0.0.1:10102:8080"
    networks:
      - datamaps-network

  datamaps-phpmyadmin:
    image: phpmyadmin
    container_name: "datamaps-phpmyadmin"
    restart: always
    environment:
      PMA_HOST: datamaps-mariadb
    depends_on:
      - datamaps-mariadb
    ports:
      - "127.0.0.1:10190:80"
    networks:
      - datamaps-network

networks:
  datamaps-network:
    driver: bridge
    name: datamaps-network
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:1:20::/112
          gateway: fd00:1:20::1

volumes:
  datamaps-db:
