name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # ou la version de votre choix
        extensions: pcov, zip, exif, pdo_mysql, mysqli
        coverage: pcov

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Security Check using local-php-security-checker
    - name: Download local-php-security-checker
      run: wget -O local-php-security-checker https://github.com/fabpot/local-php-security-checker/releases/latest/download/local-php-security-checker_2.0.6_linux_amd64 && chmod +x local-php-security-checker
      
    - name: Run security check
      run: ./local-php-security-checker

    # PHPCS Check
    - name: Check coding standards
      run: ./vendor/bin/phpcs --standard=PSR12 ./src ./tests

    # PHPStan Check
    - name: Perform static analysis on source code
      run: ./vendor/bin/phpstan analyse --level=9 ./src ./tests

    # PHPUnit Test
    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

    # Publish Test Coverage Results
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: build/logs/clover.xml
        fail_ci_if_error: true
