name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # ou la version de votre choix
        extensions: pcov, zip, exif, pdo_mysql, mysqli
        coverage: pcov


    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # PHPCS Check
    - name: Check coding standards
      run: ./vendor/bin/phpcs

    # PHPStan Check
    - name: Perform static analysis
      run: ./vendor/bin/phpstan analyse

    # PHPUnit Test
    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit